### ISSUE TITLE
How do we migrate from dimsav/laravel-translatable to Astrotomic/laravel-translatable?

### ISSUE THREAD

**Issue by wyred** [Astrotomic/laravel-translatable#10]
Hi,

Thanks for taking over the project!

I've checked the readme but don't see any info about how to switch over to this new repo/package for existing projects.

My guess is that I have to 
1. composer require this new package
2. composer remove the old one
3. update all namespaces that refer to the old package to the new one

Is there anything else I need to look out for?

Regards,
Erik

**Comment by Gummibeer** [comment]
Hey,

because it's relatively simple I haven't wrote it down. You are right - I would only swap step 1 & 2.
Will add it to the release info later.

To replace the namespace faster you can search for `Dimsav\` and replace it with `Astrotomic\`. 

The only other change included in the `v11` release is https://github.com/dimsav/laravel-translatable/pull/557 - but this shouldn't be breaking because PHP7.1 is already required by Laravel itself and also by this package.

If you get into trouble don't hesitate and write again. 😊

**Comment by Gummibeer** [comment]
I will let *stale-bot* auto-close this and keep it open for others who search for instructions.

**Comment by Gummibeer** [comment]
## migrate from dimsav to astrotomic

1. upgrade to `dimsav/laravel-translatable:v10.0.0`
2. run `composer remove dimsav/laravel-translatable`
3. run `composer require astrotomic/laravel-translatable`
4. replace `Dimsav\` by `Astrotomic\` in your whole project (namespace change)

**Comment by DanielMalmgren** [comment]
Sorry if this is a stupid question, but how do I upgrade dimsav/laravel-translatable to 10.0.0? Doing a composer upgrade here only gets me to 9.5.0. Does this version difference make any difference for a package that is to be removed anyway?

**Comment by Gummibeer** [comment]
@DanielMalmgren in general this depends on your package version constraint.
https://getcomposer.org/doc/articles/versions.md

The [v10](https://github.com/dimsav/laravel-translatable/releases/tag/v10.0.0) did three changes and all could be some kind of breaking - that's why we decided to do the major release. It wasn't clear that we will move this package which forces another major-release.
Because it could be that you also use `v8` or even lower the first step *could* be optional but because the `v11` is based on the `v10` it's recommended to do this upgrade before the namespace change. Just to be sure that everything still works. If a direct jump from `v9` to `v11` works depends on the amount of customizations you did. If you "just" use this package this should work.
