### ISSUE TITLE
Is it possible to fill the parent's id when using getTranslationOrNew?

### ISSUE THREAD

**Issue by notflip** [Astrotomic/laravel-translatable#115]
I'm wondering if there's any method, when using getTranslationOrNew, to fill the parent id? So for example when using getTranslationOrNew on a dog() table it would have dog_id pre-filled for the newly created translation. Thanks!

**Comment by Lloople** [comment]
Hi @notflip,

If I recall correctly, it's already done, but you need to define the relation in both models before that.

[Check this line](https://github.com/Astrotomic/laravel-translatable/blob/master/src/Translatable/Translatable.php#L183)

**Comment by notflip** [comment]
Ah thanks, I might have to doublecheck the relations on both tables then.

**Comment by Lloople** [comment]
@notflip after trying it out I see my solution does not work. I've never noticed this because I never used this method before, but I think the method should populate that field automatically, but I don't know how this can be done.

@Gummibeer Maybe declaring a variable on the `DogTranslation` model like `public $parentKey = 'dog_id'`? 🤔

**Comment by Gummibeer** [comment]
@Lloople thanks for your answers so far! :)

@notflip the line of interest is
https://github.com/Astrotomic/laravel-translatable/blob/f7b294cb7b2a853cb11b0e51bc60d9170f2b11a0/src/Translatable/Translatable.php#L361

The foreign/parent key is also already available via 
https://github.com/Astrotomic/laravel-translatable/blob/f7b294cb7b2a853cb11b0e51bc60d9170f2b11a0/src/Translatable/Traits/Relationship.php#L55-L62

Just to clarify: you want the `dog_id` filled after creating the new translation but before saving it?

Right now this isn't in the package. The reason why we add it right before saving is that it could be that it isn't available after creation.
```php
$dog = new Dog();
$dog->translateOrNew();
$dog->save();
```
I'm not sure if I want to add the inconsistency between new/unsaved models and already present ones.
https://github.com/Astrotomic/laravel-translatable/blob/f7b294cb7b2a853cb11b0e51bc60d9170f2b11a0/src/Translatable/Translatable.php#L176-L186
But if we move the single ID set line into a dedicated function we could call it from both places. Because if no ID is present the value will be `null` and `null` is also the default value for the foreign ID I would be fine to do so without any additional condition.

Does anyone want to create a PR? Otherwise I will try to do it.
