### ISSUE TITLE
Multilingual problem

### ISSUE THREAD

**Issue by tolgacibikci** [Astrotomic/laravel-translatable#143]
My project have 2 locale. User can change your locale.

My default setting is translatable/locale = 'tr',

But if user change your locale for 'en', 
all records return with 'tr' locale because of the my default setting.

For example:

If user locale is 'tr':

$menu->listsTranslations('name')->where('is_active', 1)->pluck('name', 'id')->toArray())

Result 
`array:3 [▼
  1 => "Ana Menü"
  2 => "Alt Menü"
]`

If user locale is 'en'
The result should be like this: 
`array:3 [▼
  1 => "Main Men"
  2 => "Sub Menu"
]`

How can I get correct locale records

**Comment by Gummibeer** [comment]
Hey,
have you specified the locale in the `translatable` config? Or only the app locale?
By default this package uses the app locale and because of this can also handle a runtime changed locale if it's done via `app()->setLocale()`.
But if you've specified the locale in package config you have to change it also or you keep it `null` to always use the current app locale.
