### ISSUE TITLE
Not get current Locale

### ISSUE THREAD

**Issue by minhvn** [Astrotomic/laravel-translatable#148]
Hi, Im got issue.
Im use 3 language, EN, FR, ES. When query, it only show EN, not show current language.

**To Reproduce**

```php
echo App::getLocale();
$cat = Category::first();
echo $cat->name;
```
Result:
ES, and NAME of EN not ES

But when get all translations, it show all 3 languages.

**Versions (please complete the following information)**
- PHP: 7x
- Database: mysql
- Laravel: 7.2
- Package: 

Thank you.

**Comment by Gummibeer** [comment]
Hey,
have you defined the package config `locale` key? If so this will override the app locale all the time.
https://github.com/Astrotomic/laravel-translatable/blob/2b7cfd6c48c5340b2d06d8edc8b6995580e64f65/src/config/translatable.php#L34-L46

That's the most common mistake. If it's still `null` it would be interesting what the packages locales helper `current()` method returns.
https://docs.astrotomic.info/laravel-translatable/package/locales-helper#current

**Comment by minhvn** [comment]
Thank for your reply, Im really define on config.
<img width="810" alt="Screen Shot 2020-05-04 at 07 14 01" src="https://user-images.githubusercontent.com/187747/80929545-05063780-8dd7-11ea-8d2c-01328fd8b36a.png">
app(Locales::class)->current() => ONLY SHOW EN.
IM USING: codezero/laravel-localized-routes to change language.
Thank you again, please help me :) @Gummibeer

**Comment by Gummibeer** [comment]
Hey, set the `locale` value in your `translatable` config to `null`. This will allow the package to use the translator/app locale instead of the hardcoded one. If you want to use different locales for the app/translator and this translatable package you have to change this config value to the value you want - possibly, like the app locale, on runtime.
For most cases this isn't needed - so it should stay `null` as it is by default and described in the config value description comment.

**Comment by minhvn** [comment]
@Gummibeer thank you very much, it's work now.
