### ISSUE TITLE
Using SoftDeletes

### ISSUE THREAD

**Issue by bally86** [Astrotomic/laravel-translatable#151]
Hi,

I'm using the Laravel SoftDeletes for deleting my models. Also for deleting the translations.
With the withTrashed scope I can update my (soft)deleted records. But the translations don't get updated. Instead a new record is created. How can I skip the "deleted_at IS NULL" from the query for checking of translation existance?

```
$value = ProductValueModel::withTrashed()->updateOrCreate(
    [
        'specification_id' => 10,
        'product_id' => 12,
        'division_id' => 1
    ],

    [
        'name' => 'Test'
    ]
);
```

**Comment by Gummibeer** [comment]
You would have to adjust several parts of the package to apply the `withTrashed()` scope to all necessary queries.
I can also tell you that soft delete support will never be a goal of this package because they are only a pain to handle and there's nearly never a reason for soft deletes. Most times they are misused in replacement of backups, archives, disabled/banned/... flags and so on.
In addition they slow down every query because of an additional condition on a, by default, not indexed column.

If you have one of these rare cases where soft deletes are the right solution and you want to stick with them - this won't be the first/last package that doesn't work without adjustments with soft deletes.
