### ISSUE TITLE
Can this package be used with a single polymorphic model?

### ISSUE THREAD

**Issue by MordiSacks** [Astrotomic/laravel-translatable#152]
Instead of having
posts, posts_translations,   
articles, articles_translations,   
etc..
can I have 
articles, posts, 

and translations, something like this
```php
        Schema::create('translations', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string("translatable_type");
            $table->unsignedBigInteger("translatable_id");
            $table->string('column', 70);
            $table->string('locale', 5);
            $table->text('value');
            $table->timestamps();
            $table->unique([
                'translatable_type',
                'translatable_id',
                'column',
                'locale',
            ], 'translations_u_type_id_column_locale');
        });
```

**Comment by Gummibeer** [comment]
Hey,
yes you can use a single polymorphic table as long as this table contains all possible translatable columns.
You will have to override the `translations()` relationship method to use a polymorphic relation instead of a simple `hasMany()` and you will have to define the `$translationModel` property.
But the package isn't made and also not tested for polymorphic translations. So this could always break or require more adjustments.
Could also be that some of the scopes don't work because they only query the ID and not the type column.

**Comment by MordiSacks** [comment]
@Gummibeer 
Thank you  for your response, I will test this asap
and report result

**Comment by overclocked555** [comment]
@MordiSacks , hello! Of course, a lot of time has passed. :-) 
Were you able to implement the polymorphic model?
