### ISSUE TITLE
$translatedAttributes keys also need to be in $fillable otherwise not saving

### ISSUE THREAD

**Issue by adzchappers** [Astrotomic/laravel-translatable#153]
**Describe the bug**
The only way I can get this to work is by having the translated attribute keys be duplicated in teh fillable array. PHP 7.3, Laravel 7

`
    class MyModelextends Model implements TranslatableContract
    {
        use Translatable;

        public $translatedAttributes = ['discussion'];

        protected $fillable = [
            'column_1',
            'column_2',
            'discussion'
        ];
    }
`

According to the website, https://docs.astrotomic.info/laravel-translatable/installation, this shouldn't be done.

**Comment by Gummibeer** [comment]
Hey,

could you get into more detail? How you set the attribute on the model for example? And what happens if you don't have the attribute in `$fillable`?

https://github.com/Astrotomic/laravel-translatable/blob/2b7cfd6c48c5340b2d06d8edc8b6995580e64f65/src/Translatable/Translatable.php#L115-L138

The trait overrides the `fill()` method and doesn't run the default/core `fill()` if the attribute is translatable. So there is no fillable check on the main model for translatable attributes.

**Comment by afbora** [comment]
**Not working** without adding translated attributes to fillable:

````php
protected $fillable = ['slug'];
protected $translatedAttributes= ['name'];

$product->update(['name' => 'Foo]);
````

**Working** with adding translated attributes to fillable:

````php
protected $fillable = ['name', 'slug'];
protected $translatedAttributes= ['name'];

$product->update(['name' => 'Foo]);
````

**Comment by Gummibeer** [comment]
Hey,

nearly every test-case in `\Astrotomic\Translatable\Tests\TranslatableTest` uses mass-assignment without having the translatable attributes listed as fillable and all are passing.

> OK (142 tests, 313 assertions)

If you can add/PR a failing testcase that demonstrates your issue I will investigate what happens.

Otherwise it will be hard to investigate further. The method that handles the translatable attributes without require them to be fillable on the main model is `\Astrotomic\Translatable\Translatable::fill()`.

**Comment by Gummibeer** [comment]
@afbora happy that you found the issue. :)
I think that the documentation can be improved at this point and highlight this sentence more prominent.

> The important is to define your locales and stick to them.

**Comment by Gummibeer** [comment]
Have adjusted the documentation: https://github.com/Astrotomic/laravel-translatable/commit/7d94ce688e96b83c515f477e1df54bef3f9eb597#diff-11d8910b58f5c70ccb3bedc0f37c892f

should be clearer now what and how to configure: https://docs.astrotomic.info/laravel-translatable/installation

**Comment by afbora** [comment]
> If you can add/PR a failing testcase that demonstrates your issue I will investigate what happens.

I will try soon.

Thank you for great support @Gummibeer 👍
