### ISSUE TITLE
Dynamically add languages

### ISSUE THREAD

**Issue by atefrihane** [Astrotomic/laravel-translatable#160]
Hey everyone

I would like to know is there a way to dynamically add languages within this package ?

I tried to use Laravel `Config::set()` but changes are not persistent!

Anyone can help me ?

**Comment by Gummibeer** [comment]
Hey,

The package comes with its own `Locales` service class. If you've changed the config you will have to call `load()` on it to let the package know about it.
If you only want to add (not remove) locales I would recommend to use the `add()` method of named service. Keep in mind that this locales class is the one and only source of truth for this package (on runtime). So if you need the list of locales somewhere else you should use this class - otherwise your lists could differ which could result in undefined locale exceptions.
