### ISSUE TITLE
need to connect to my language table

### ISSUE THREAD

**Issue by saber13812002** [Astrotomic/laravel-translatable#165]
in my project they want me to connect this module into my tranlation table 

we have language table that want to connect languages to this module

can you help me to how to apply those changes in module?

i think i need to change Locales.php then create new fork then publish my changes into packagist and install my forked package 

 public function getLanguageFromCountryBasedLocale(string $locale): string
    {
        return explode($this->getLocaleSeparator(), $locale)[0];
    }

**Comment by Gummibeer** [comment]
Hey,

sorry for the delay.
You could extend the `Locales` class and rebind yours to the container.
You should only override the `load()` method.
https://github.com/Astrotomic/laravel-translatable/blob/70811609331f10e3a068970632de1705133baa22/src/Translatable/Locales.php#L86-L107

Everything else should automatically work from there. So instead of reading from config you could get the locales from your database.
