### ISSUE TITLE
Scope whereTranslationLike case insensitive variant for PostgreSQL needed?

### ISSUE THREAD

**Issue by KMB** [Astrotomic/laravel-translatable#17]
Hello

We use PostgreSQL and would need a case insensitive variant (i.e. ILIKE) of the whereTranslationLike scope, or a similar alternative.

Basically:
```php
public function scopeOrWhereTranslationILike(Builder $query, string $translationField, $value, ?string $locale = null)
{
    return $this->scopeWhereTranslation($query, $translationField, $value, $locale, 'orWhereHas', 'ILIKE');
}
```

which works great. Is there an easy way to "attach" this to the package, that would also make it update-proof? So either for everbody in the next release or somewhere in our Laravel installation outside the vendor-directory?

I tried to use the LOWER(xxx) instead, but this resulted in

`product_translations.LOWER(name)`

which obviously doesn't work.

Love the package, btw! Switch to Astrotomic was easy as pie.

**Comment by Gummibeer** [comment]
Hey,
thanks for your input and your kind words. :) 

Because this package is designed to work with all (laravel supported) databases I wouldn't like to add database-type specific methods like your described one.
Primary because since `v11.1.0` we have the unified scopes from #2 (you already found). So it's super easy to add your own scopes.
In your case I would recommend to implement your own `Translatable` trait which uses the package one and there you can add your missing logic. The scopes are `public` and even if not listed in the interface (good question why, should we add scopes which are some kind of magic methods to the interface?) they are part of the public API and will cause a BC if changed in a not backward compatible way.
So you will be safe to add this scope by your own. I'm also pretty sure that we won't add a method with the same name in the package itself at any time.

**Comment by KMB** [comment]
> In your case I would recommend to implement your own Translatable trait which uses the package one and there you can add your missing logic. 

Thx, I will take a look at this.
