### ISSUE TITLE
How to log Model event with spatie activitylog package?

### ISSUE THREAD

**Issue by weidmaster** [Astrotomic/laravel-translatable#186]
Hello, I started doing some tests with the Spatie Activitylog package, to make and auditing of sorts in my application. Now I have an issue that when I change a Model that has translations, it doesn't log the translated changes because the field is in another table, of course.

I think I will need to manually log the activities instead of relying on the automatic way of Model events that the Spatie package provides, but maybe there is a way to make it work with the events?

Here is the package link for reference (https://spatie.be/docs/laravel-activitylog/v2)

The code I am using to setup automatic log:
```php
use LogsActivity;

    protected static $logName = 'generalsetting';
    protected static $logFillable = true;
    protected static $logOnlyDirty = true;
```

**Comment by Gummibeer** [comment]
Hey,

Welcome back again. 😉👋
As one of my favorite answers to activitylog questions since we've added it: use `tapActivity()` method on your model.
https://spatie.be/docs/laravel-activitylog/v3/advanced-usage/logging-model-events#tap-activity-before-logged-from-event
It allows you to manipulate the activity recorded on your main model before the activity is written to the database.
This would be the easest if you want/can build the diff logic your own or are fine with logging only the new values.

Another idea could be to use the longer locale aware attribute notation the translatable package offers in the `protected static $logAttributes` array - so you could try to log `name:en` and `name:de`. Haven't tried it but as the activitylog package supports accessors it could work.

If none of them works  would like to ask you to open an issue in the activitylog package as I can label it with the *package compatibility* label and possibly it gets even solved during Hacktoberfest. 😉

**Comment by weidmaster** [comment]
It is always good to be back. I just noticed you maintain both packages so it is interesting as you can help with both.

```tapActivity()```is implemented in v3, so it is not compatible with L5.6. I can't update Laravel at the moment, so I will try to log the longer locale aware attributes. But then I will need to add all fillable attributes manually either way 😛 

Maybe it would work if use the trait in the Translatable models as well?

I will do the tests but it would be cool to have the package compatibility indeed, as it sounds natural for them to work together ❤️

**Comment by Gummibeer** [comment]
You can combine `$logFillable` with `$logAttributes` - it will merge the list together.
https://github.com/spatie/laravel-activitylog/blob/271fb767675e3afda46b59ed69557ee2d62937b1/src/Traits/DetectsChanges.php#L33-L58

So you only have to list the additional attributes in `$logAttributes`. I think that the explicit list of translatable attributes is easier anyway then managing it in the `tap()` callback.

You could even get fancy with this snippet:

```php
public function attributesToBeLogged()
{
    $attributes = parent::attributesToBeLogged();

    foreach($this->getLocalesHelper()->all() as $locale) {
        foreach ($this->translatedAttributes as $field) {
            $attributes[] = $field.':'.$locale;
        }
    }

    return $attributes;
}
```

Depending on where you place this method and where you import the traits it could be that you would have to use aliased trait method import instead of `parent` call.
https://www.php.net/manual/en/language.oop5.traits.php#language.oop5.traits.conflict

**Comment by weidmaster** [comment]
Indeed the ```$logFillable```and ```$logAttributes``` does get merged. I tried to put the trait in the Translation model and it does work, so I get two logs, one for the main model and one for the translation one. So far it is all right, but then I used ```$logOnlyDirty```and it does not log the locale field because it never changes lol.

So I used ```$logAttributes = ['locale']```but I had to remove the only dirty option. It is not ideal. So it would be nice to have an option to log a field no matter what I guess, or to inject the locale on the changes.

I will try to implement your method suggestion, maybe it will work to pass the locale and so even if it double logs each Model, it should be fine.

---

I tested the longer locale aware name in main model and it does not work at all.

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-activitylog/pull/801 could provide an easier way to log changes.

**Comment by weidmaster** [comment]
> [spatie/laravel-activitylog#801](https://github.com/spatie/laravel-activitylog/pull/801) could provide an easier way to log changes.

Yes that looks good. I will do some tests. Right now I am using tapActivity() to log extra attributes
