### ISSUE TITLE
A tip to make translations for a Pivot Model

### ISSUE THREAD

**Issue by scil** [Astrotomic/laravel-translatable#19]
After an instance of Pivot Model is saved, it's attributes does not add `id`, because
```php
// Illuminate\Database\Eloquent\Model

if ($this->getIncrementing()) {
    $this->insertAndSetId($query, $attributes);
}

```
And 
```php
// Illuminate\Database\Eloquent\Relations\Pivot

public $incrementing = false;
```

If `id` not added into attributes, laravel-translatable can not insert translations data properly.

So,  to make translations for a Pivot Model,  add this to this Model
```php
public $incrementing = true;
```

**Comment by Gummibeer** [comment]
Hey,

so do you want us to add functionality which sets `$incrementing` to `true` by default if the model is a pivot model? Or do you just want to add this for others to know and optional added to the documentation?

I don't want to set model properties from within the trait this would just move the error to the query which exits because the `id` column does not exist.
So if added to the code I would like more a check which throws a readable exception if the model is a pivot one but the `$incrementing` is set to `false`. But even this case could throw an error falsy because the user decided to don't use incrementing keys but UUIDs for example.

So my favorite would be to add a new page to the docs which describes the usage in pivot models.

**Comment by scil** [comment]
yes , i'm on your board

i'd like to share this tip, avoiding errors and debug.

**Comment by Gummibeer** [comment]
@scil would you like to add a documentation page for this? I've never used translated pivot models so I could only copy what you wrote here but can't extend it by example code and/or some more hints - if needed.

**Comment by Gummibeer** [comment]
https://docs.astrotomic.info/laravel-translatable/usage/pivot-model
