### ISSUE TITLE
Get all translations best practice

### ISSUE THREAD

**Issue by rezaffm** [Astrotomic/laravel-translatable#219]
Hi (Moin),

I hope you are well.

I have apparently a fairly easy question for you, but I wondered what would be the best way to solve this one.

Let's say we have pages and page_translations tables. On pages we have id as a column and on page_translations we have id, page_id, locale, title,...., and so on.

Now, in the admin panel we basically want to treat this relationship as if the page table is not there. Basically, just showing all pages. For instance, let's say we have 1 page translated in 'de' and 'en'. Basically this means we have two pages 'de foo' and 'en foo'.

In the table we want to show both pages as if they exist on their own. 

There are several ways to solve this. For instance, we could simply loop over the PageTranslation Model. However, when caching is implemented this maybe becomes tricky as apparently there will be only a Page Repository (always eager loading translations).

And an alternative solution would be a simple join like this one:

`$pages = Page::join('page_translations as pt', 'pages.id', '=', 'pt.page_id')
  ->select('pages.*', 'pt.locale', 'pt.title', 'pt.page_status')
  ->take(5)
  ->get();
`

Then one could easily loop over the result as if the PageTranslation model wouldn't exist at all.

Fairly easy question for you and I was just wondering what's the best practices to solve this one.

**Comment by Gummibeer** [comment]
Hey,

at very first I have a wish/recommendation: use "easy" and similar words far less. 😉
https://alexjs.com is a great tool for it. The reason is that only because it seems or is easy to you it doesn't have to others and can be part of gate keeping. I know that this can be super hard as we use these words like easy, simple, just, only so often and normal. But it will help you and your environment/community. 🚀

Now your question. I would get for the `PageTranslation::all()` approach in your scenario. Caching is always a hard topic and should be one of the last steps to optimize performance as it comes with a lot of complexity and possible problems.
So don't know what, why or how you are caching but your caching should never reduce your abilities to query the database.

**Comment by rezaffm** [comment]
Hi pal,

no worries about the use of easy, I ll reduce it and thanks for the heads up.

Well, the way I cache (or want to) is to use Repositories wrapped with decorators. I have translations for posts, pages, questions, categories, tags,..., and I felt that it might be an overkill to add a separate repository for each model. Therefore, I was thinking to only have a Repository (with respective decorator) for all the main models.

For now, I went with the PageTranslation::all() approch but was wondering what experiences you made. So If I understand you correctly, you typically work with Repositories for each model, so you have a Page Repository, PageTranslation Repository et cetera - correct?

**Comment by Gummibeer** [comment]
Hey,

typically I don't use repositories. 😅
Caching whole queries can bring you into big troubles - at least if you have a write intensive app. I recommend you to optimize the queries itself as an optimized query runs nearly the same as a redis call. The heavy job is most times model hydration not the DB call itself.

In case you have performance issues I can recommend you to use laravel debugbar and check the queries tab. If there's one in hundreds microseconds or above: find it and play with it.
It can help to add an index, use sub queries instead of joins, remove eager loading and/or use cursor instead of fetching all at once. Jonathan Reinink has an awesome course about squeezing performance of eloquent.

But your original question was direct query or join and I would recommend direct query. Always faster than a join. The only case I would say that you should use the page itself is if you have global scopes like soft deletes, drafts or whatever that should be applied.

**Comment by rezaffm** [comment]
Yes, you are right. The project I am working on is still young, but I am getting a lot of traffic recently, and I thought of using the repository pattern with decorators to prepare for more traffic. At the moment I am at 1.000 - 2.000 a month but will be soon at > 5.000 clicks or more, >10.000/20.000 towards the end of the year.

The queries itself are all optimized without any n+1 problems and always eager loading. Google page speed is at 100 for all the relevant sites, for the rest it is more in the range of 90-95 (yes, I am a psycho...).

Maybe I am over-stressing the thing a bit too much ... :-)
