### ISSUE TITLE
map models to laravel-translations translation table using [lang, group, key, value]

### ISSUE THREAD

**Issue by chrillep** [Astrotomic/laravel-translatable#288]
**Is your feature request related to a problem? Please describe.**
mapping models translatable attributes to a single translations table

**Describe the solution you'd like**
using a single translations table for every models translatable attribute.

**Describe alternatives you've considered**
writing it myself :)

**Additional context**
Since laravel-translation is good at handling translations ex. editing, import, export.
whats missing is a connection to an actual/ if needed model for each translation.
The bridge would be using [laravel-translatable](https://github.com/Astrotomic/laravel-translatable)
to connect laravel-translation language/translations to models.
refs:
* https://github.com/joedixon/laravel-translation
* https://github.com/joedixon/laravel-translation/tree/2.x/database/migrations
* https://github.com/joedixon/nova-translation
* https://github.com/kraenkvisuell/nova-astrotranslatable

relates:
* https://github.com/Astrotomic/laravel-translatable/issues/60

**Comment by Gummibeer** [comment]
Hey,
it's not what this package aims to achieve as the dedicated translation models allow to cast, validate and observe each translation type. And also allows more efficient queries than a simple key-value table.
In case you want a more simple solution you can check out https://github.com/spatie/laravel-translatable as they are using JSON columns instead of dedicated models/tables.
