### ISSUE TITLE
the locale is 'en' but the translation comes 'ar'

### ISSUE THREAD

**Issue by johnef** [Astrotomic/laravel-translatable#29]
**Describe the bug**
I removed `dimsav/laravel-translatable` using the steps you mention [here ](https://github.com/Astrotomic/laravel-translatable/issues/10#issuecomment-503932092)
replaced `Dimsav\ by Astrotomic\` in my whole project
but when I change the locale to `en` every static translations on page comes `en` but the dynamic translations comes from the database comes `ar`.

**To Reproduce**
Here is an example of my code
**Model**
```
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;

class ProductCategory extends Model implements TranslatableContract {
	use Translatable;
	public $translatedAttributes = [ 'name' ];
	protected $fillable = [ 'image', 'soft_delete' ];
}
```

**Controller**
```
public function menu() {
		$categories = ( new ProductCategory )
			->translatedIn( 'en' )
			->where( 'soft_delete', 0 )->with( 'categoryProduct' )
			->whereHas( 'categoryProduct', function ( $query ) {
				$query->where( 'product_category_id', '!=', null )
				->where( 'soft_delete', 0 );
			} )
			->withCount( 'categoryProduct' )
			->orderBy( 'sort_categories', 'ASC' )
			->orderBy( 'category_product_count', 'desc' )
			->get();
		return $categories;
	}
```
**Migrations**
```
Schema::create( 'product_category_translations', function ( Blueprint $table ) {
			$table->increments( 'id' );
			$table->integer( 'product_category_id' )->unsigned();
			$table->string( 'name', 255 );
			$table->string( 'locale' )->index();
			$table->unique( [ 'product_category_id', 'locale' ] );
			$table->foreign( 'product_category_id' )->references( 'id' )->on( 'product_categories' )->onDelete( 'cascade' );
		} );
```

**Expected behavior**
I should see the translation coming from database `en`

**Versions (please complete the following information)**
- PHP: 7.3.5
- Database: 5.7
- Laravel: 5.8
- Package: "astrotomic/laravel-translatable": "^11.1"

**Exception**
No thrown exception message.

**Comment by Gummibeer** [comment]
@johnef I beliefe that I know where the issue is.
The `translatedIn( 'en' )` scope checks only if an `en` translation exists. If you want to use the english  translation you will have to set the app locale to `en` and have translatable config locale `null` https://github.com/Astrotomic/laravel-translatable/blob/master/src/config/translatable.php#L46 or you set the translatable config locale to `en`.
https://github.com/Astrotomic/laravel-translatable/blob/8ec38419ef538e1e973dace59503299462dfca05/src/Translatable/Locales.php#L46-L49
this is used to get the current locale in which the translated fields are shown.
