### ISSUE TITLE
How To Load Translations With Specific Columns Only

### ISSUE THREAD

**Issue by vijaybajrot** [Astrotomic/laravel-translatable#48]
Migration same as package document.
https://docs.astrotomic.info/laravel-translatable/installation

**My Current code is :** 
```php
$posts = Post::withTranslation()->get();
```
**Wants this :** 
```php
$posts = Post::withTranslation(['title'])->get();
// I have `title:varchar`, `description:text` columns in database
```

**Comment by Gummibeer** [comment]
I'm sorry but this isn't possible at the moment. My primary "problem" with this is that we rely heavily on the `translations` relation and loading them only partial would created unwanted behavior if you access `$post->description`.

So is your request because of performance? Or do you just want to only return the `title` in your API or somewhere?
In this case you could use the `only()` or `makeHidden()` methods.

**Comment by nekooee** [comment]
> Migration same as package document. https://docs.astrotomic.info/laravel-translatable/installation
> 
> **My Current code is :**
> 
> ```
> $posts = Post::withTranslation()->get();
> ```
> 
> **Wants this :**
> 
> ```
> $posts = Post::withTranslation(['title'])->get();
> // I have `title:varchar`, `description:text` columns in database
> ```

if you need to select columns for better performance, you should use `with('translations')` : like this:

```php
  $articles = Article::where('publish', true)
            ->with(['translations' => fn($query) => $query
                ->where('locale', app()->getLocale())
                ->select('article_id','title','locale')
            ])
            ->latest()->get();
```
Do not forget that it is required to select the article_id and locale columns.
