### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation or all foreign keys are zero.

### ISSUE THREAD

**Issue by stelasido** [Astrotomic/laravel-translatable#50]
If I use in my migrations (car_translations table):
`$table->foreign('car_id')->references('id')->on('cars')->onDelete('cascade');`
then I am getting this error:
> SQLSTATE[23000]: Integrity constraint violation
, because some how the library can't get the id of the parent table (cars) inserted row, but there is an inserted row in the parent table (cars).
If I don't use that relation in `cars_translations` table:
``$table->foreign('car_id')->references('id')->on('cars')->onDelete('cascade');``
 all `car_id`'s are zero. in `cars_translations` table.

I am using your example from the home page, but what I am doing different is that, I need to set the id of the `cars` table manual:
`	    $data = [
	    	'id' => 89,
		    'en' => ['name' => 'My first post'],
		    'fr' => ['name' => 'Mon premier post'],
	    ];

	    $post = Car::create($data);`

**Comment by stelasido** [comment]
Ok, I have setup the parent's table id to be increment and still can manual set up it and it works, but I think this is a bug.

**Comment by Gummibeer** [comment]
After the main model is saved we use `getKey()` to get the primary key of the main model.
Have you flagged the `id` as fillable in your main model? Otherwise it won't set the value and without an increment it wouldn't have an ID.

Could you check what `$car->getKey()` returns if you save it without a translation value?
