### ISSUE TITLE
RuleFactory doesn't parse the array value

### ISSUE THREAD

**Issue by buzzclue** [Astrotomic/laravel-translatable#53]
I am trying to validate **require_with** content key with all locales is replaced fine but values doesn't get replaced.

```php
$rules = [
    'title' => 'required',
    '%content%' => "required_with:%title%,%description%",
    'en.content' => 'required', //make default locale required.
];
$rules = RuleFactory::make($rules, RuleFactory::FORMAT_ARRAY );
```
Output is:
```php
array:3 [
  "title" => "required"
  "en.content" => "required"
  "fr.content" => "required_with:%icon%,%title%,%description%"
]
```

RuleFactory doesn't parse the array value? or am i missing something?

**Comment by buzzclue** [comment]
This worked for me, i will create a pull request. :)
```php
foreach ($this->locales as $locale) {
    $rules[$this->formatKey($locale, $key)] = $this->formatKey($locale, $value);
}
```

**Comment by Gummibeer** [comment]
Hey,

yes this is a limitation at the moment.
The reason is that the possible values in the rule list are "endless".

It could be a string (single rule). It could be a string (comma separated multiple rules). It could be an array of mixed. It could be an instance of the rule interface. And if I'm not fully wrong also a closure.

Next the intention. Not everyone wants to require description if title is present in same locale. Possible usecases could also be to require title in any locale.

I would like to extend the rule factory but these are the reasons why we decided against it at first until we get issues.

I don't want to stop you! And you also don't have to handle all these cases. I'm fine with limited solutions.
But it shouldn't break if something else happens. And I would like to introduce `formatRule()` even if it does the same for the moment.

**Comment by Gummibeer** [comment]
https://github.com/Astrotomic/laravel-translatable/releases/tag/v11.5.0
