### ISSUE TITLE
How to check if translatable title is nullable in data base

### ISSUE THREAD

**Issue by tursunbaevz** [Astrotomic/laravel-translatable#57]
**Models:** Post, PostTranslatable
Let's say i have 3 localizations: 'en', 'ru', 'fr'
'en' title is 'Some title'
'ru' title is 'Заголовок'
'fr' title is '(**empty**)' 
and if i go to **_localhost/fr/posts_** i see empty title but tied styles are still there(:
How can i check if `posts->title` (fr) or other languages are null and hide images, styles from PostModel

Pls any help

**Comment by Gummibeer** [comment]
https://docs.astrotomic.info/laravel-translatable/package/scopes the `translatedIn()` scope will help if there is no `fr` row at all.
Otherwise you could extend the basic `whereTranslation()` scope by a new `whereNotTranslation()` one - would also accept a PR for this.
This could be used to check if a specific translation attribute is (not) empty.

If you already loaded all records and just want to check in PHP: `empty($post->title)` will do the trick.

But if the title is required I would recommend to use the first idea and prevent empty rows.
