### ISSUE TITLE
Polymorphic Relationships?

### ISSUE THREAD

**Issue by buzzclue** [Astrotomic/laravel-translatable#60]
Does translatable handle polymorphic relationships?  do you have a test or example that explains how to handle polymorphism?

**Comment by Gummibeer** [comment]
Which part should be polymorph? What exactly is your issue?
At the end it's an additional relationship on top of the translated model. So it isn't relevant if the translated model is also part of another polymorphic relationship.

Or do you want to make the translations relationship polymorph?

**Comment by buzzclue** [comment]
Yes i am trying to morph translations relation. 
> Or do you want to make the translations relationship polymorph?

**Comment by Gummibeer** [comment]
So a single translation table for several translated models?
This should be possible if you replace the `translations` relationship. The `translation` relationship should adjust automatically.
After this everything should work because everything is based on the relationship.

**Comment by buzzclue** [comment]
Sorry i got busy with different stuff.

So this is the structure i have that i am converting with this package:

```php 
Schema::create('posts', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
            $table->bigIncrements('id');
            $table->unsignedBigInteger('author_id')->index()->unsigned();
            $table->enum('visibility', ['public', 'link', 'private'])->index();
            $table->boolean('translations')->default(0);
            $table->timestamps();
            $table->softDeletes();
            $table->foreign('author_id')->references('id')->on('users')->onDelete('cascade');
});

Schema::create('post_translations', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
            $table->bigIncrements('id');
            $table->string('locale')->index();
            $table->unsignedBigInteger('post_id');
            $table->morphs('postable');
            $table->string('post_key');
            $table->text('post_value');
            $table->unique(['post_id', 'locale', 'post_key']);

            $table->foreign('post_id')->references('id')->on('posts')->onDelete('cascade');
});
//i know i probably don't need the post_id because i am using morph.

class Post extends Model
{
    use Translatable;

    protected $table = 'posts';
    public $translationForeignKey = 'post_id';

    public $translatedAttributes =['locale', 'post_id', 'postable_type',  'postable_id', 'post_key', 'post_value'];
    protected $fillable = ['author_id', 'visibility', 'translations'];

    public function settings()
    {
        return $this->morphMany(PostTranslation::class, 'postable');
    }
}

class PostTranslation extends Model
{
    public $timestamps = false;

    protected $table = 'post_translations';

    protected $fillable = ['locale', 'post_id', 'postable_type',  'postable_id', 'post_key', 'post_value'];

    public function postable()
    {
        return $this->morphTo();
    }
}
```

How can i use this polymorphic relation? there are multiple entry points for each post which i am saving in key/value relation. Is there a way make it work?

**Comment by gavinhewitt** [comment]
> So a single translation table for several translated models?
> This should be possible if you replace the `translations` relationship. The `translation` relationship should adjust automatically.
> After this everything should work because everything is based on the relationship.

Noob question but how do you exactly replace the translations relationship? Simply overwriting the method does not work:

![image](https://user-images.githubusercontent.com/1969103/71352364-6a6b3180-2576-11ea-8322-8b7fc94c1a07.png)

**Comment by Gummibeer** [comment]
Hey @gavinhewitt 
It's because, like Phpstorm says, that you missed the return type definition.
https://www.php.net/manual/en/functions.returning-values.php

In your case you have to add `: HasMany` behind `translations()` - you will have to add the `use` statement (phpstorm will do it if you accept autocompletion.
```php
public function translations(): HasMany
{
    // ...
}
```

**Comment by gavinhewitt** [comment]
> Hey @gavinhewitt
> It's because, like Phpstorm says, that you missed the return type definition.
> https://www.php.net/manual/en/functions.returning-values.php
> 
> In your case you have to add `: HasMany` behind `translations()` - you will have to add the `use` statement (phpstorm will do it if you accept autocompletion.
> 
> ```
> public function translations(): HasMany
> {
>     // ...
> }
> ```

Thanks for the fast reply!

However, I did add the return type initially but for the polymorphic relation to work you need to return not a HasMany but a MorphMany. If you do so PHPStorm will complain that the return type is incorrect, which makes sense because the return type is defined in the Translatable contract. Therefore my question if you need to bypass the contract, which is what I did now. It works but may not be the preferred way of tackling it.

Is my assumption correct?

**Comment by Gummibeer** [comment]
@gavinhewitt you are right. We would have to change it to `HasOneOrMany` to support polymorphism - after a quick check in the core GitHub - haven't tried it.
I would accept a PR for this change if it solves your issue. You could easily check it by changing it in the vendor folder.
PS: you would need PHP7.4 to use a different return type declaration that extends the basic one. Otherwise you have to use the interface one and just return an object that extends the return type.

**Comment by Lloople** [comment]
What about removing the typehint for this case? From my point of view it can be considered a bug and changing the typehint won’t solve it in previous versions of PHP

**Comment by Gummibeer** [comment]
@Lloople it's not a bug if the user isn't able to change a relationship type. Because it alters the package core relationship and isn't part of the packages scope.
If there is an easy way, like changing the return type, to allow this - I'm fine with it.
But I won't remove or weaken a return type. I'm a fan of strong type systems and happy that PHP evolves in this area.
I also don't have a problem that every user who wants to change the core relationship has to use PHP 7.4+ because it's a bonus feature that's not part of the package documented/wanted use.

**Comment by gavinhewitt** [comment]
@Gummibeer For now I'm good, having bigger issues to worry about :-) One of which is that this package is probably not meant to use for polymorphic relations. Retrieving models seems to work just fine, it's the saving that gives me a headache. I figured out that I can set `public $translationForeignKey = 'model_id';` to the key I need. However, the model_type I had to set hard in `saveTranslations()`, like so:

```
$translation->setAttribute('model_type', str_replace('Translation', '', $this->getTranslationModelNameDefault()));
```
Is there another way to set it?

**Comment by gavinhewitt** [comment]
Scrap that last comment. Fixed it by adding this to the translation model:

```
public $attributes = [
        'model_type' => 'App\Models\Term'
    ];
```

**Comment by Gummibeer** [comment]
@gavinhewitt happy that you found a solution.
Would be great if you could create a gist with the necessary files after you found a full working solution.
With this I could check if we can improve the package and add it to the docs.

Wish you and all your family a Merry Christmas!
🎅🎄🎁🦌⛄❄️🍭🍬🍫🍗🥧🍮🍷🍽️👨‍👩‍👧‍👦

**Comment by chrillep** [comment]
hmm this seems like it would be nice if you would like all models to be mapped to a [translation table](https://github.com/joedixon/laravel-translation/blob/2.x/database/migrations/2018_08_29_205156_create_translations_table.php#L16-L26) as in https://github.com/joedixon/laravel-translation

since laravel-translation and laravel-translatable have a different usecases .

however unifying usage would really be good.

so using laravel-translatable for translating models and editing/import/export the translations using laravel-translation
