### ISSUE TITLE
Mutator - main model

### ISSUE THREAD

**Issue by front-stream** [Astrotomic/laravel-translatable#68]
Is is possible to run mutator on main model?

I have main model - `Team`

    class Team extends Model implements TranslatableContract{
        use Translatable;

        public $translatedAttributes = [
            'name'
        ];`

and model fo translations: `TeamTranslation`

    class TeamTranslation extends Model{
        public $timestamps = false;
        protected $fillable = [
            'name',
        ];

I would like to define mutator on main model (Team).

    public function getNameAttribute($value){
        return $value.'__'.$this->another_property_from_team_model;
    }

It seems that it does not work... What you suggest?

**Comment by Gummibeer** [comment]
Hey,
Haven't tested it but found this part.
https://github.com/Astrotomic/laravel-translatable/blob/7df7da63666679d20fa410cc7969be1f037fea89/src/Translatable/Translatable.php#L131-L138
But won't have time to dive into it this weekend. Will check it further, if still needed, next week.

**Comment by weidmaster** [comment]
Hello! It's me again, now with the same question regarding Mutators. I figured the package does retrieve the default locale for a mutator, but it is not returning it for other translations.

I have the following mutator in a Model:
```php
public function getMetaTagAttribute($value)
    {
        if($value == null)
        {
            return '';
        }
        return explode(',', $value);
    }
```

Testing with Tinker gives me the following:
![Captura de Tela 2020-07-24 às 10 22 25](https://user-images.githubusercontent.com/9614642/88395514-96ae9100-cd97-11ea-821a-b62f2a18223a.png)

I didn't find how to make it work in the documentation, so I need guidance, @Gummibeer

**Comment by Gummibeer** [comment]
Hey,

this is true and intended. Because `translate()` returns an instance of the translation model which has it's own mutators. You could move the mutator into the translation model. This should work for both of your examples.
But I would also recommend to use the built in `array` cast instead of this custom one. But to make this work you will have to switch to JSON. Just an idea, I always liked the built in more than a custom one, primary because there are some edge-cases which makes writing custom string to array casts a pain. 🤯

**Comment by weidmaster** [comment]
I do prefer the built-in solutions too. It is just that in this inherited codebase it is all setup like that. I will test moving the mutator to the translation model and I will take a look about this json field and array cast. Thank you.
